### ISSUE TITLE
Crash at Tom's Simple Storage mod Crafting Terminal when searching for an item

### ISSUE THREAD

**Issue by WimpieRatte** [melontini/recipe_book_is_pain#12]
I originally logged this as a bug on Tom's Simple Storage mod: https://github.com/tom5454/Toms-Storage/issues/199

With "Recipe Book Is Pain" installed alongside the mod, searching for contents in its terminals crashes the client.
After investigating, he found that the problem was caused by "Recipe Book Is Pain", so I'm logging this here, just in case you're able to fix it?

This was on version 1.19.2.

Crash report is attached.
[crash-2023-02-21_13.06.59-client.txt](https://github.com/melontini/recipe_book_is_pain/files/10834925/crash-2023-02-21_13.06.59-client.txt)

**Comment by melontini** [comment]
Hi, thanks for the report!

I can't tell you right away, but looking at the error, `java.lang.NullPointerException: Cannot assign field "field_22764" because "this.nextPageButton" is null` something is not initialized correctly. 

The `nextPageButton` should be initialized by the `reset` method of the `RecipeBookWidget`. So, my current guess is that `reset` is not called in time.

**Comment by melontini** [comment]
I can't reproduce this issue, there may be something more going on here. Search doesn't sync (I'm not sure if this is related to [cracker-util](https://github.com/melontini/cracker-util/blob/master/src/main/java/me/melontini/crackerutil/mixin/recipe_book_helper/pages/RecipeBookWidgetMixin.java), tho), but it doesn't crash either. 

![2023-02-27](https://user-images.githubusercontent.com/104443436/221530934-d1b744a8-85b8-422a-a99d-0ec1636f9fb0.png)

**Comment by WimpieRatte** [comment]
hmm... not sure if it's related to any of the other mods then, but I do know that removing the recipe-book-is-pain mod stopped the crash. Maybe it's related to EMI being there as well? Because there's another bug that Tom mentioned was happening with EMI active, that prevented someone from removing an item from the terminal. However, disabling EMI (ctr+o), allowed me to remove the items. This might be related to the search issue?

**Comment by melontini** [comment]
Doesn't seem to be the case. 

Are you playing a modpack by any chance? If so, can you link it?

If not, the only thing I can suggest is to disable half of your mods (except RBIP and Tom's Storage) until you find the not-crashing combo.

**Comment by WimpieRatte** [comment]
They actually released a new version that fixed a compatibility issue they had with EMI as well.
This might be related - will check it out.
If I encounter this again, I'll confirm the results :)

**Comment by melontini** [comment]
After looking into [Toms-Storage's](https://github.com/tom5454/Toms-Storage) code a bit further. It seems that the `updateSearch();` method in AbstractStorageTerminalScreen (parent of CraftingTerminalScreen) is called before the recipe book's `reset()` method is called.

The crash only occurs when the recipe book is closed.

The mods crash together because:
1. The RecipeBookWidget is created, and since the book is closed, the `reset` method is skipped.
2. CraftingTerminalScreen tries to update the recipe book by calling `refreshTabButtons()` and since CrackerUtil injects code which requires calling the `reset` method, the game crashes.

```java
        //AbstractStorageTerminalScreen

        @Override
	protected void init() {
                //... more code here ...

		buttonCtrlMode = addRenderableWidget(new GuiButton(leftPos - 18, topPos + 5 + 18*3, 3, b -> {
			controllMode = (controllMode + 1) % ControllMode.VALUES.length;
			buttonCtrlMode.state = controllMode;
			sendUpdate();
		}));
		updateSearch(); // <- attempts to update search
	}
```

```java
        //CraftingTerminalScreen 

        @Override
	protected void onUpdateSearch(String text) {
		if(FabricLoader.getInstance().isModLoaded("roughlyenoughitems") || (searchType & 4) > 0) {
			if(recipeBookGui.searchBox != null)recipeBookGui.searchBox.setValue(text);
			recipeBookGui.recipesUpdated(); // <- refreshTabButtons() in different mappings
		}
	}
```

```java
    //RecipeBookWidgetMixin

   @Inject(at = @At("HEAD"), method = "refreshTabButtons", cancellable = true)
    private void cracker_util$refresh(CallbackInfo ci) {
        //... more code here ...

        --wc;
        this.pages = MathStuff.fastCeil(wc / 6);
        updatePages();
        updatePageSwitchButtons(); // <- this is where th game crashes, because the  `reset` method is skipped.
        ci.cancel();
    }
```

```java
    //RecipeBookWidgetMixin

    @Unique
    @Override
    public void updatePageSwitchButtons() {
        this.nextPageButton.visible = this.pages > 0 && this.page < this.pages; // <- this field right here.
        this.prevPageButton.visible = this.pages > 0 && this.page != 0;
    }
```

This will be patched in the next version of CrackerUtil
