### ISSUE TITLE
[Bug] Crash with Charm + Supplementaries

### ISSUE THREAD

**Issue by SplendidAlakey** [melontini/recipe_book_is_pain#14]
**Describe the bug**

If Recipe Book is Pain installed together with [Charm](https://www.curseforge.com/minecraft/mc-mods/charm) and [Supplementaries](https://www.curseforge.com/minecraft/mc-mods/supplementaries), and creative tabs option in Supplmenetaries is turned on, the game crashes on startup.

**To Reproduce**

1. Install RBIP, Charm and Supplementaries
2. Launch the game once to generate configs, it will not crash
3. Now set `"creative_tab": true` in `supplementaries-common.json`
4. Launch the game again and crash

**Expected behavior**

No crash.

**Logs**

https://gist.github.com/SplendidAlakey/aa0ff0dd7dc1e9b7434afdf4c26ce264

**Environment:**

 - Minecraft Version 1.19.2
 - Mod Version 0.8.1-1.18

**Additional context**

The crash doesn't happen on Quilt.

**Comment by melontini** [comment]
Wow, that's impressive, a three-way.

Right now, it looks like Charm initialized the CharmClientHacks class. Which calls the RecipeBookGroup enum, during enum's initialization, RBIP runs through all the ItemGroups trying to get the icon, with the config option on, Supplmenetaries tries to supply an icon for the group, but for some reason `GLOBE_ITEM.get().getDefaultInstance()` returns null and the game crashes.

I assume that this doesn't happen on the cracker-util version, since its initialization depends on a different class.

I'll try to replicate cracker's way of extending enums here.

**Comment by melontini** [comment]
This version should work. https://github.com/melontini/recipe_book_is_pain/actions/runs/4675835219

I'll publish it on MR and CF once you confirm that it works.
