### ISSUE TITLE
Items and entire tabs are missing.

### ISSUE THREAD

**Issue by tossrid** [melontini/recipe_book_is_pain#7]
Title. I thought maybe only the alternative/grouped recipes were showing up, but Adorn (the first tab) has multiple recipes like that, and it doesn't show up at all.
<details><summary>Creative tab, mods: Adorn, Comforts, Gravity API and Plushie-Mod.</summary><img src="https://user-images.githubusercontent.com/109666448/179968413-4b56ce3c-3862-42b6-8ce0-5d1149a8e632.png"></details>
<details><summary>Recipe book, only Comforts shows up, and it's incomplete.</summary><img src="https://user-images.githubusercontent.com/109666448/179969493-a8a4b73c-f752-424f-bf47-b0a224fb8b2e.png"></details>

**Comment by melontini** [comment]
Hey, I believe you didn't unlock all recipes yet.

Could you try running:
`/recipe give @s *`

If that is the case, [Better Recipe Books](https://www.curseforge.com/minecraft/mc-mods/brb) has an option to unlock all recipes instantly.

**Comment by melontini** [comment]
Weird...

Could you please tell me mod version, Minecraft version, mod loader and possibly latest.log?

**Comment by melontini** [comment]
I figured out where Adorn's items went. 

Adorn adds it's items to 2 creative tabs and since recipe book can't have items in 2 groups, they got auto-sorted to decoration blocks.

And it seems like Gravity API has no craftable items.

**Comment by melontini** [comment]
Well, I can't replicate this issue

<details>
  <summary>Recipe Book Screenshot</summary>

![recipe_book](https://user-images.githubusercontent.com/104443436/180021272-ccd685bb-dc6d-40a9-bff9-7db7afacdfeb.png)

</details>

The log has no related errors, and even the `[RBIP] recipe book init complete` message is where it should be. (Which is not the case in some packs)

I've also noticed that the combat category is missing entirely.
So, my only guess is there was an error whilst adding to RecipeBookGroup enum. Since the way I add to that enum is not recommended by Fabric wiki itself. [(link)](https://fabricmc.net/wiki/tutorial:enum_adding?rev=1634419205)
There is a different way, but it doesn't fit my case.

As for mugs, the mug is probably in the food category. Other drinks must be made via Brewer.

**Comment by tossrid** [comment]
I am so stupid, and I am so sorry.
I wasn't using the **goddamn** crafting table.

Coming fresh off of other recipe viewers I was expecting it to show everything, and since I never used the vanilla recipe book it didn't even cross my mind that you need to use the correct crafting block.

I'm really sorry for wasting your time.

That being said, there's no recipe book for Brewer. I didn't expect it to anyway, and I'm not sure what mod's problem that is, just thought I'd let you know.
